run:
  timeout: '5m'
  build-tags:
    - all
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - gocyclo
    - gocognit
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 10  # alert
  gocognit:
    min-complexity: 15  # alert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default-severity: error
