// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: notes.proto

package notes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotesClient is the client API for Notes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotesClient interface {
	SaveNote(ctx context.Context, in *SaveNoteRequest, opts ...grpc.CallOption) (*SaveNoteResponse, error)
	ListNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNotesResponse, error)
	GetNoteByID(ctx context.Context, in *GetNoteByIDRequest, opts ...grpc.CallOption) (*GetNoteByIDResponse, error)
	DeleteNoteByID(ctx context.Context, in *DeleteNoteByIDRequest, opts ...grpc.CallOption) (*DeleteNoteByIDResponse, error)
	UpdateNoteByID(ctx context.Context, in *UpdateNoteByIDRequest, opts ...grpc.CallOption) (*UpdateNoteByIDResponse, error)
}

type notesClient struct {
	cc grpc.ClientConnInterface
}

func NewNotesClient(cc grpc.ClientConnInterface) NotesClient {
	return &notesClient{cc}
}

func (c *notesClient) SaveNote(ctx context.Context, in *SaveNoteRequest, opts ...grpc.CallOption) (*SaveNoteResponse, error) {
	out := new(SaveNoteResponse)
	err := c.cc.Invoke(ctx, "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/SaveNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) ListNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/ListNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) GetNoteByID(ctx context.Context, in *GetNoteByIDRequest, opts ...grpc.CallOption) (*GetNoteByIDResponse, error) {
	out := new(GetNoteByIDResponse)
	err := c.cc.Invoke(ctx, "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/GetNoteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) DeleteNoteByID(ctx context.Context, in *DeleteNoteByIDRequest, opts ...grpc.CallOption) (*DeleteNoteByIDResponse, error) {
	out := new(DeleteNoteByIDResponse)
	err := c.cc.Invoke(ctx, "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/DeleteNoteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesClient) UpdateNoteByID(ctx context.Context, in *UpdateNoteByIDRequest, opts ...grpc.CallOption) (*UpdateNoteByIDResponse, error) {
	out := new(UpdateNoteByIDResponse)
	err := c.cc.Invoke(ctx, "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/UpdateNoteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotesServer is the server API for Notes service.
// All implementations must embed UnimplementedNotesServer
// for forward compatibility
type NotesServer interface {
	SaveNote(context.Context, *SaveNoteRequest) (*SaveNoteResponse, error)
	ListNotes(context.Context, *emptypb.Empty) (*ListNotesResponse, error)
	GetNoteByID(context.Context, *GetNoteByIDRequest) (*GetNoteByIDResponse, error)
	DeleteNoteByID(context.Context, *DeleteNoteByIDRequest) (*DeleteNoteByIDResponse, error)
	UpdateNoteByID(context.Context, *UpdateNoteByIDRequest) (*UpdateNoteByIDResponse, error)
	mustEmbedUnimplementedNotesServer()
}

// UnimplementedNotesServer must be embedded to have forward compatible implementations.
type UnimplementedNotesServer struct {
}

func (UnimplementedNotesServer) SaveNote(context.Context, *SaveNoteRequest) (*SaveNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveNote not implemented")
}
func (UnimplementedNotesServer) ListNotes(context.Context, *emptypb.Empty) (*ListNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedNotesServer) GetNoteByID(context.Context, *GetNoteByIDRequest) (*GetNoteByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoteByID not implemented")
}
func (UnimplementedNotesServer) DeleteNoteByID(context.Context, *DeleteNoteByIDRequest) (*DeleteNoteByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNoteByID not implemented")
}
func (UnimplementedNotesServer) UpdateNoteByID(context.Context, *UpdateNoteByIDRequest) (*UpdateNoteByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNoteByID not implemented")
}
func (UnimplementedNotesServer) mustEmbedUnimplementedNotesServer() {}

// UnsafeNotesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotesServer will
// result in compilation errors.
type UnsafeNotesServer interface {
	mustEmbedUnimplementedNotesServer()
}

func RegisterNotesServer(s grpc.ServiceRegistrar, srv NotesServer) {
	s.RegisterService(&Notes_ServiceDesc, srv)
}

func _Notes_SaveNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).SaveNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/SaveNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).SaveNote(ctx, req.(*SaveNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/ListNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).ListNotes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_GetNoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).GetNoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/GetNoteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).GetNoteByID(ctx, req.(*GetNoteByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_DeleteNoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).DeleteNoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/DeleteNoteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).DeleteNoteByID(ctx, req.(*DeleteNoteByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notes_UpdateNoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesServer).UpdateNoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes/UpdateNoteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesServer).UpdateNoteByID(ctx, req.(*UpdateNoteByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notes_ServiceDesc is the grpc.ServiceDesc for Notes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitlab.ozon.dev.go.classroom_12.students.week_3_workshop.pkg.notes.v1.Notes",
	HandlerType: (*NotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveNote",
			Handler:    _Notes_SaveNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _Notes_ListNotes_Handler,
		},
		{
			MethodName: "GetNoteByID",
			Handler:    _Notes_GetNoteByID_Handler,
		},
		{
			MethodName: "DeleteNoteByID",
			Handler:    _Notes_DeleteNoteByID_Handler,
		},
		{
			MethodName: "UpdateNoteByID",
			Handler:    _Notes_UpdateNoteByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notes.proto",
}
