version: '3.8'

services:
  cart:
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    command: ["/app/cartbuild"]
    ports:
      - "8082:8082" #http
      - "6060:6060" #pprof
    env_file:
      - ./cart/.env
    depends_on:
      - loms

  loms:
    build:
      context: .
      dockerfile: ./loms/Dockerfile
    command: ["/app/lomsbuild"]
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
    env_file:
      - ./loms/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: loms
      POSTGRES_PASSWORD: loms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686" #ui
      - "4318:4318" #collector

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
