package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i week-2-workshop/cart/internal/service/cart/item/add.repository -o ./cart/internal/service/cart/item/add/mock/repository_mock.go -n RepositoryMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"week-2-workshop/cart/internal/domain"

	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements add.repository
type RepositoryMock struct {
	t minimock.Tester

	funcAddItem          func(ctx context.Context, userID int64, item domain.Item) (err error)
	inspectFuncAddItem   func(ctx context.Context, userID int64, item domain.Item)
	afterAddItemCounter  uint64
	beforeAddItemCounter uint64
	AddItemMock          mRepositoryMockAddItem
}

// NewRepositoryMock returns a mock for add.repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddItemMock = mRepositoryMockAddItem{mock: m}
	m.AddItemMock.callArgs = []*RepositoryMockAddItemParams{}

	return m
}

type mRepositoryMockAddItem struct {
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockAddItemExpectation
	expectations       []*RepositoryMockAddItemExpectation

	callArgs []*RepositoryMockAddItemParams
	mutex    sync.RWMutex
}

// RepositoryMockAddItemExpectation specifies expectation struct of the repository.AddItem
type RepositoryMockAddItemExpectation struct {
	mock    *RepositoryMock
	params  *RepositoryMockAddItemParams
	results *RepositoryMockAddItemResults
	Counter uint64
}

// RepositoryMockAddItemParams contains parameters of the repository.AddItem
type RepositoryMockAddItemParams struct {
	ctx    context.Context
	userID int64
	item   domain.Item
}

// RepositoryMockAddItemResults contains results of the repository.AddItem
type RepositoryMockAddItemResults struct {
	err error
}

// Expect sets up expected params for repository.AddItem
func (mmAddItem *mRepositoryMockAddItem) Expect(ctx context.Context, userID int64, item domain.Item) *mRepositoryMockAddItem {
	if mmAddItem.mock.funcAddItem != nil {
		mmAddItem.mock.t.Fatalf("RepositoryMock.AddItem mock is already set by Set")
	}

	if mmAddItem.defaultExpectation == nil {
		mmAddItem.defaultExpectation = &RepositoryMockAddItemExpectation{}
	}

	mmAddItem.defaultExpectation.params = &RepositoryMockAddItemParams{ctx, userID, item}
	for _, e := range mmAddItem.expectations {
		if minimock.Equal(e.params, mmAddItem.defaultExpectation.params) {
			mmAddItem.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddItem.defaultExpectation.params)
		}
	}

	return mmAddItem
}

// Inspect accepts an inspector function that has same arguments as the repository.AddItem
func (mmAddItem *mRepositoryMockAddItem) Inspect(f func(ctx context.Context, userID int64, item domain.Item)) *mRepositoryMockAddItem {
	if mmAddItem.mock.inspectFuncAddItem != nil {
		mmAddItem.mock.t.Fatalf("Inspect function is already set for RepositoryMock.AddItem")
	}

	mmAddItem.mock.inspectFuncAddItem = f

	return mmAddItem
}

// Return sets up results that will be returned by repository.AddItem
func (mmAddItem *mRepositoryMockAddItem) Return(err error) *RepositoryMock {
	if mmAddItem.mock.funcAddItem != nil {
		mmAddItem.mock.t.Fatalf("RepositoryMock.AddItem mock is already set by Set")
	}

	if mmAddItem.defaultExpectation == nil {
		mmAddItem.defaultExpectation = &RepositoryMockAddItemExpectation{mock: mmAddItem.mock}
	}
	mmAddItem.defaultExpectation.results = &RepositoryMockAddItemResults{err}
	return mmAddItem.mock
}

// Set uses given function f to mock the repository.AddItem method
func (mmAddItem *mRepositoryMockAddItem) Set(f func(ctx context.Context, userID int64, item domain.Item) (err error)) *RepositoryMock {
	if mmAddItem.defaultExpectation != nil {
		mmAddItem.mock.t.Fatalf("Default expectation is already set for the repository.AddItem method")
	}

	if len(mmAddItem.expectations) > 0 {
		mmAddItem.mock.t.Fatalf("Some expectations are already set for the repository.AddItem method")
	}

	mmAddItem.mock.funcAddItem = f
	return mmAddItem.mock
}

// When sets expectation for the repository.AddItem which will trigger the result defined by the following
// Then helper
func (mmAddItem *mRepositoryMockAddItem) When(ctx context.Context, userID int64, item domain.Item) *RepositoryMockAddItemExpectation {
	if mmAddItem.mock.funcAddItem != nil {
		mmAddItem.mock.t.Fatalf("RepositoryMock.AddItem mock is already set by Set")
	}

	expectation := &RepositoryMockAddItemExpectation{
		mock:   mmAddItem.mock,
		params: &RepositoryMockAddItemParams{ctx, userID, item},
	}
	mmAddItem.expectations = append(mmAddItem.expectations, expectation)
	return expectation
}

// Then sets up repository.AddItem return parameters for the expectation previously defined by the When method
func (e *RepositoryMockAddItemExpectation) Then(err error) *RepositoryMock {
	e.results = &RepositoryMockAddItemResults{err}
	return e.mock
}

// AddItem implements add.repository
func (mmAddItem *RepositoryMock) AddItem(ctx context.Context, userID int64, item domain.Item) (err error) {
	mm_atomic.AddUint64(&mmAddItem.beforeAddItemCounter, 1)
	defer mm_atomic.AddUint64(&mmAddItem.afterAddItemCounter, 1)

	if mmAddItem.inspectFuncAddItem != nil {
		mmAddItem.inspectFuncAddItem(ctx, userID, item)
	}

	mm_params := &RepositoryMockAddItemParams{ctx, userID, item}

	// Record call args
	mmAddItem.AddItemMock.mutex.Lock()
	mmAddItem.AddItemMock.callArgs = append(mmAddItem.AddItemMock.callArgs, mm_params)
	mmAddItem.AddItemMock.mutex.Unlock()

	for _, e := range mmAddItem.AddItemMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddItem.AddItemMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddItem.AddItemMock.defaultExpectation.Counter, 1)
		mm_want := mmAddItem.AddItemMock.defaultExpectation.params
		mm_got := RepositoryMockAddItemParams{ctx, userID, item}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddItem.t.Errorf("RepositoryMock.AddItem got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddItem.AddItemMock.defaultExpectation.results
		if mm_results == nil {
			mmAddItem.t.Fatal("No results are set for the RepositoryMock.AddItem")
		}
		return (*mm_results).err
	}
	if mmAddItem.funcAddItem != nil {
		return mmAddItem.funcAddItem(ctx, userID, item)
	}
	mmAddItem.t.Fatalf("Unexpected call to RepositoryMock.AddItem. %v %v %v", ctx, userID, item)
	return
}

// AddItemAfterCounter returns a count of finished RepositoryMock.AddItem invocations
func (mmAddItem *RepositoryMock) AddItemAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItem.afterAddItemCounter)
}

// AddItemBeforeCounter returns a count of RepositoryMock.AddItem invocations
func (mmAddItem *RepositoryMock) AddItemBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItem.beforeAddItemCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.AddItem.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddItem *mRepositoryMockAddItem) Calls() []*RepositoryMockAddItemParams {
	mmAddItem.mutex.RLock()

	argCopy := make([]*RepositoryMockAddItemParams, len(mmAddItem.callArgs))
	copy(argCopy, mmAddItem.callArgs)

	mmAddItem.mutex.RUnlock()

	return argCopy
}

// MinimockAddItemDone returns true if the count of the AddItem invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockAddItemDone() bool {
	for _, e := range m.AddItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddItemCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItem != nil && mm_atomic.LoadUint64(&m.afterAddItemCounter) < 1 {
		return false
	}
	return true
}

// MinimockAddItemInspect logs each unmet expectation
func (m *RepositoryMock) MinimockAddItemInspect() {
	for _, e := range m.AddItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.AddItem with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddItemCounter) < 1 {
		if m.AddItemMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepositoryMock.AddItem")
		} else {
			m.t.Errorf("Expected call to RepositoryMock.AddItem with params: %#v", *m.AddItemMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItem != nil && mm_atomic.LoadUint64(&m.afterAddItemCounter) < 1 {
		m.t.Error("Expected call to RepositoryMock.AddItem")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockAddItemInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddItemDone()
}
