// Code generated by http://github.com/gojuno/minimock (v3.3.12). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/service.productClient -o product_client_mock.go -n ProductClientMock -p mocks

import (
	"route256/cart/pkg/product"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProductClientMock implements service.productClient
type ProductClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetProduct          func(skuID uint32) (pp1 *product.Product, err error)
	inspectFuncGetProduct   func(skuID uint32)
	afterGetProductCounter  uint64
	beforeGetProductCounter uint64
	GetProductMock          mProductClientMockGetProduct
}

// NewProductClientMock returns a mock for service.productClient
func NewProductClientMock(t minimock.Tester) *ProductClientMock {
	m := &ProductClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductMock = mProductClientMockGetProduct{mock: m}
	m.GetProductMock.callArgs = []*ProductClientMockGetProductParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProductClientMockGetProduct struct {
	optional           bool
	mock               *ProductClientMock
	defaultExpectation *ProductClientMockGetProductExpectation
	expectations       []*ProductClientMockGetProductExpectation

	callArgs []*ProductClientMockGetProductParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// ProductClientMockGetProductExpectation specifies expectation struct of the productClient.GetProduct
type ProductClientMockGetProductExpectation struct {
	mock      *ProductClientMock
	params    *ProductClientMockGetProductParams
	paramPtrs *ProductClientMockGetProductParamPtrs
	results   *ProductClientMockGetProductResults
	Counter   uint64
}

// ProductClientMockGetProductParams contains parameters of the productClient.GetProduct
type ProductClientMockGetProductParams struct {
	skuID uint32
}

// ProductClientMockGetProductParamPtrs contains pointers to parameters of the productClient.GetProduct
type ProductClientMockGetProductParamPtrs struct {
	skuID *uint32
}

// ProductClientMockGetProductResults contains results of the productClient.GetProduct
type ProductClientMockGetProductResults struct {
	pp1 *product.Product
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProduct *mProductClientMockGetProduct) Optional() *mProductClientMockGetProduct {
	mmGetProduct.optional = true
	return mmGetProduct
}

// Expect sets up expected params for productClient.GetProduct
func (mmGetProduct *mProductClientMockGetProduct) Expect(skuID uint32) *mProductClientMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductClientMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.paramPtrs != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by ExpectParams functions")
	}

	mmGetProduct.defaultExpectation.params = &ProductClientMockGetProductParams{skuID}
	for _, e := range mmGetProduct.expectations {
		if minimock.Equal(e.params, mmGetProduct.defaultExpectation.params) {
			mmGetProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProduct.defaultExpectation.params)
		}
	}

	return mmGetProduct
}

// ExpectSkuIDParam1 sets up expected param skuID for productClient.GetProduct
func (mmGetProduct *mProductClientMockGetProduct) ExpectSkuIDParam1(skuID uint32) *mProductClientMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductClientMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &ProductClientMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.skuID = &skuID

	return mmGetProduct
}

// Inspect accepts an inspector function that has same arguments as the productClient.GetProduct
func (mmGetProduct *mProductClientMockGetProduct) Inspect(f func(skuID uint32)) *mProductClientMockGetProduct {
	if mmGetProduct.mock.inspectFuncGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("Inspect function is already set for ProductClientMock.GetProduct")
	}

	mmGetProduct.mock.inspectFuncGetProduct = f

	return mmGetProduct
}

// Return sets up results that will be returned by productClient.GetProduct
func (mmGetProduct *mProductClientMockGetProduct) Return(pp1 *product.Product, err error) *ProductClientMock {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductClientMockGetProductExpectation{mock: mmGetProduct.mock}
	}
	mmGetProduct.defaultExpectation.results = &ProductClientMockGetProductResults{pp1, err}
	return mmGetProduct.mock
}

// Set uses given function f to mock the productClient.GetProduct method
func (mmGetProduct *mProductClientMockGetProduct) Set(f func(skuID uint32) (pp1 *product.Product, err error)) *ProductClientMock {
	if mmGetProduct.defaultExpectation != nil {
		mmGetProduct.mock.t.Fatalf("Default expectation is already set for the productClient.GetProduct method")
	}

	if len(mmGetProduct.expectations) > 0 {
		mmGetProduct.mock.t.Fatalf("Some expectations are already set for the productClient.GetProduct method")
	}

	mmGetProduct.mock.funcGetProduct = f
	return mmGetProduct.mock
}

// When sets expectation for the productClient.GetProduct which will trigger the result defined by the following
// Then helper
func (mmGetProduct *mProductClientMockGetProduct) When(skuID uint32) *ProductClientMockGetProductExpectation {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductClientMock.GetProduct mock is already set by Set")
	}

	expectation := &ProductClientMockGetProductExpectation{
		mock:   mmGetProduct.mock,
		params: &ProductClientMockGetProductParams{skuID},
	}
	mmGetProduct.expectations = append(mmGetProduct.expectations, expectation)
	return expectation
}

// Then sets up productClient.GetProduct return parameters for the expectation previously defined by the When method
func (e *ProductClientMockGetProductExpectation) Then(pp1 *product.Product, err error) *ProductClientMock {
	e.results = &ProductClientMockGetProductResults{pp1, err}
	return e.mock
}

// Times sets number of times productClient.GetProduct should be invoked
func (mmGetProduct *mProductClientMockGetProduct) Times(n uint64) *mProductClientMockGetProduct {
	if n == 0 {
		mmGetProduct.mock.t.Fatalf("Times of ProductClientMock.GetProduct mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProduct.expectedInvocations, n)
	return mmGetProduct
}

func (mmGetProduct *mProductClientMockGetProduct) invocationsDone() bool {
	if len(mmGetProduct.expectations) == 0 && mmGetProduct.defaultExpectation == nil && mmGetProduct.mock.funcGetProduct == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProduct.mock.afterGetProductCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProduct.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProduct implements service.productClient
func (mmGetProduct *ProductClientMock) GetProduct(skuID uint32) (pp1 *product.Product, err error) {
	mm_atomic.AddUint64(&mmGetProduct.beforeGetProductCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProduct.afterGetProductCounter, 1)

	if mmGetProduct.inspectFuncGetProduct != nil {
		mmGetProduct.inspectFuncGetProduct(skuID)
	}

	mm_params := ProductClientMockGetProductParams{skuID}

	// Record call args
	mmGetProduct.GetProductMock.mutex.Lock()
	mmGetProduct.GetProductMock.callArgs = append(mmGetProduct.GetProductMock.callArgs, &mm_params)
	mmGetProduct.GetProductMock.mutex.Unlock()

	for _, e := range mmGetProduct.GetProductMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProduct.GetProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProduct.GetProductMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProduct.GetProductMock.defaultExpectation.params
		mm_want_ptrs := mmGetProduct.GetProductMock.defaultExpectation.paramPtrs

		mm_got := ProductClientMockGetProductParams{skuID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.skuID != nil && !minimock.Equal(*mm_want_ptrs.skuID, mm_got.skuID) {
				mmGetProduct.t.Errorf("ProductClientMock.GetProduct got unexpected parameter skuID, want: %#v, got: %#v%s\n", *mm_want_ptrs.skuID, mm_got.skuID, minimock.Diff(*mm_want_ptrs.skuID, mm_got.skuID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProduct.t.Errorf("ProductClientMock.GetProduct got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProduct.GetProductMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProduct.t.Fatal("No results are set for the ProductClientMock.GetProduct")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProduct.funcGetProduct != nil {
		return mmGetProduct.funcGetProduct(skuID)
	}
	mmGetProduct.t.Fatalf("Unexpected call to ProductClientMock.GetProduct. %v", skuID)
	return
}

// GetProductAfterCounter returns a count of finished ProductClientMock.GetProduct invocations
func (mmGetProduct *ProductClientMock) GetProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.afterGetProductCounter)
}

// GetProductBeforeCounter returns a count of ProductClientMock.GetProduct invocations
func (mmGetProduct *ProductClientMock) GetProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.beforeGetProductCounter)
}

// Calls returns a list of arguments used in each call to ProductClientMock.GetProduct.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProduct *mProductClientMockGetProduct) Calls() []*ProductClientMockGetProductParams {
	mmGetProduct.mutex.RLock()

	argCopy := make([]*ProductClientMockGetProductParams, len(mmGetProduct.callArgs))
	copy(argCopy, mmGetProduct.callArgs)

	mmGetProduct.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductDone returns true if the count of the GetProduct invocations corresponds
// the number of defined expectations
func (m *ProductClientMock) MinimockGetProductDone() bool {
	if m.GetProductMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductMock.invocationsDone()
}

// MinimockGetProductInspect logs each unmet expectation
func (m *ProductClientMock) MinimockGetProductInspect() {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductClientMock.GetProduct with params: %#v", *e.params)
		}
	}

	afterGetProductCounter := mm_atomic.LoadUint64(&m.afterGetProductCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && afterGetProductCounter < 1 {
		if m.GetProductMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ProductClientMock.GetProduct")
		} else {
			m.t.Errorf("Expected call to ProductClientMock.GetProduct with params: %#v", *m.GetProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && afterGetProductCounter < 1 {
		m.t.Error("Expected call to ProductClientMock.GetProduct")
	}

	if !m.GetProductMock.invocationsDone() && afterGetProductCounter > 0 {
		m.t.Errorf("Expected %d calls to ProductClientMock.GetProduct but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductMock.expectedInvocations), afterGetProductCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetProductInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductDone()
}
