@startuml

actor User as u
collections Cart as c
database CartStorage as cs
collections ProductService as p

u -> c : GET /user/<user_id>/cart
activate c
c -> cs : cart.GetItemsByUserID
alt cart exists
  loop for each item in cart
    c -> p : get_product\n- token\n- sku
    activate p
    p -> c : Response:\n- name\n- price
    deactivate p
    c -> c : calculate total price
  end
  c -> u : Response:\n- []item\n- total_price
else
  c -> u : 404 Not Found
end
deactivate c

@enduml
